insert into categories (id, name) values (1, 'Framing (Steel)');
insert into categories (id, name) values (2, 'Rebar & Wire Mesh Install');
insert into categories (id, name) values (3, 'Structural and Misc Steel (Fabrication)');
insert into categories (id, name) values (4, 'Masonry & Precast');
insert into categories (id, name) values (5, 'Prefabricated Aluminum Metal Canopies');
insert into categories (id, name) values (6, 'Masonry');
insert into categories (id, name) values (7, 'Granite Surfaces');
insert into categories (id, name) values (8, 'Marlite Panels (FED)');
insert into categories (id, name) values (9, 'Drywall & Acoustical (FED)');
insert into categories (id, name) values (10, 'Fire Protection');
insert into categories (id, name) values (11, 'RF Shielding');
insert into categories (id, name) values (12, 'Epoxy Flooring');
insert into categories (id, name) values (13, 'Painting & Vinyl Wall Covering');
insert into categories (id, name) values (14, 'Roofing (Metal)');
insert into categories (id, name) values (15, 'Framing (Wood)');
insert into categories (id, name) values (16, 'Glass & Glazing');
insert into categories (id, name) values (17, 'Roofing (Metal)');
insert into categories (id, name) values (18, 'Ornamental Railings');
insert into categories (id, name) values (19, 'Epoxy Flooring');
insert into categories (id, name) values (20, 'Epoxy Flooring');
insert into categories (id, name) values (21, 'EIFS');
insert into categories (id, name) values (22, 'Casework');
insert into categories (id, name) values (23, 'Construction Clean and Final Clean');
insert into categories (id, name) values (24, 'Casework');
insert into categories (id, name) values (25, 'Landscaping & Irrigation');
insert into categories (id, name) values (26, 'Structural & Misc Steel Erection');
insert into categories (id, name) values (27, 'Ornamental Railings');
insert into categories (id, name) values (28, 'Roofing (Asphalt)');
insert into categories (id, name) values (29, 'Drilled Shafts');
insert into categories (id, name) values (30, 'Epoxy Flooring');
insert into categories (id, name) values (31, 'Ornamental Railings');
insert into categories (id, name) values (32, 'Site Furnishings');
insert into categories (id, name) values (33, 'Masonry & Precast');
insert into categories (id, name) values (34, 'Roofing (Asphalt)');
insert into categories (id, name) values (35, 'EIFS');
insert into categories (id, name) values (36, 'Waterproofing & Caulking');
insert into categories (id, name) values (37, 'Wall Protection');
insert into categories (id, name) values (38, 'Drilled Shafts');
insert into categories (id, name) values (39, 'Framing (Wood)');
insert into categories (id, name) values (40, 'Drywall & Acoustical (FED)');
insert into categories (id, name) values (41, 'Ornamental Railings');
insert into categories (id, name) values (42, 'Curb & Gutter');
insert into categories (id, name) values (43, 'Retaining Wall and Brick Pavers');
insert into categories (id, name) values (44, 'Hard Tile & Stone');
insert into categories (id, name) values (45, 'Casework');
insert into categories (id, name) values (46, 'Soft Flooring and Base');
insert into categories (id, name) values (47, 'Masonry & Precast');
insert into categories (id, name) values (48, 'Plumbing & Medical Gas');
insert into categories (id, name) values (49, 'Rebar & Wire Mesh Install');
insert into categories (id, name) values (50, 'Painting & Vinyl Wall Covering');
insert into categories (id, name) values (51, 'Rebar & Wire Mesh Install');
insert into categories (id, name) values (52, 'Roofing (Metal)');
insert into categories (id, name) values (53, 'Marlite Panels (FED)');
insert into categories (id, name) values (54, 'Structural and Misc Steel (Fabrication)');
insert into categories (id, name) values (55, 'Elevator');
insert into categories (id, name) values (56, 'Drywall & Acoustical (MOB)');
insert into categories (id, name) values (57, 'Exterior Signage');
insert into categories (id, name) values (58, 'Roofing (Metal)');
insert into categories (id, name) values (59, 'Waterproofing & Caulking');
insert into categories (id, name) values (60, 'Granite Surfaces');
insert into categories (id, name) values (61, 'Drywall & Acoustical (FED)');
insert into categories (id, name) values (62, 'Structural & Misc Steel Erection');
insert into categories (id, name) values (63, 'Drywall & Acoustical (FED)');
insert into categories (id, name) values (64, 'Drywall & Acoustical (FED)');
insert into categories (id, name) values (65, 'Fire Sprinkler System');
insert into categories (id, name) values (66, 'Marlite Panels (FED)');
insert into categories (id, name) values (67, 'Ornamental Railings');
insert into categories (id, name) values (68, 'Sitework & Site Utilities');
insert into categories (id, name) values (69, 'Electrical');
insert into categories (id, name) values (70, 'Drilled Shafts');
insert into categories (id, name) values (71, 'Drywall & Acoustical (FED)');
insert into categories (id, name) values (72, 'Masonry');
insert into categories (id, name) values (73, 'RF Shielding');
insert into categories (id, name) values (74, 'Framing (Steel)');
insert into categories (id, name) values (75, 'Soft Flooring and Base');
insert into categories (id, name) values (76, 'Structural and Misc Steel (Fabrication)');
insert into categories (id, name) values (77, 'Overhead Doors');
insert into categories (id, name) values (78, 'HVAC');
insert into categories (id, name) values (79, 'RF Shielding');
insert into categories (id, name) values (80, 'Painting & Vinyl Wall Covering');
insert into categories (id, name) values (81, 'Painting & Vinyl Wall Covering');
insert into categories (id, name) values (82, 'Marlite Panels (FED)');
insert into categories (id, name) values (83, 'Glass & Glazing');
insert into categories (id, name) values (84, 'Elevator');
insert into categories (id, name) values (85, 'Drilled Shafts');
insert into categories (id, name) values (86, 'Exterior Signage');
insert into categories (id, name) values (87, 'Electrical');
insert into categories (id, name) values (88, 'Curb & Gutter');
insert into categories (id, name) values (89, 'Structural and Misc Steel (Fabrication)');
insert into categories (id, name) values (90, 'Structural and Misc Steel (Fabrication)');
insert into categories (id, name) values (91, 'EIFS');
insert into categories (id, name) values (92, 'Framing (Steel)');
insert into categories (id, name) values (93, 'Fire Sprinkler System');
insert into categories (id, name) values (94, 'Drywall & Acoustical (FED)');
insert into categories (id, name) values (95, 'Fire Protection');
insert into categories (id, name) values (96, 'Masonry & Precast');
insert into categories (id, name) values (97, 'EIFS');
insert into categories (id, name) values (98, 'Masonry');
insert into categories (id, name) values (99, 'Asphalt Paving');
insert into categories (id, name) values (100, 'Epoxy Flooring');