-- Thêm dữ liệu bảng users

insert into users (id, username, password) values (1, 'Honorable', 'Rosie');
insert into users (id, username, password) values (2, 'Mrs', 'Seedull');
insert into users (id, username, password) values (3, 'Honorable', 'Bernath');
insert into users (id, username, password) values (4, 'Dr', 'Gurling');
insert into users (id, username, password) values (5, 'Ms', 'Bridgewood');
insert into users (id, username, password) values (6, 'Mr', 'Rawnsley');
insert into users (id, username, password) values (7, 'Ms', 'Taffs');
insert into users (id, username, password) values (8, 'Honorable', 'Stefi');
insert into users (id, username, password) values (9, 'Rev', 'Slides');
insert into users (id, username, password) values (10, 'Rev', 'Giorgione');
insert into users (id, username, password) values (11, 'Mr', 'Klemke');
insert into users (id, username, password) values (12, 'Honorable', 'Serck');
insert into users (id, username, password) values (13, 'Honorable', 'Marchment');
insert into users (id, username, password) values (14, 'Mrs', 'Effaunt');
insert into users (id, username, password) values (15, 'Mrs', 'Gircke');
insert into users (id, username, password) values (16, 'Honorable', 'McLarens');
insert into users (id, username, password) values (17, 'Rev', 'Burch');
insert into users (id, username, password) values (18, 'Honorable', 'Earl');
insert into users (id, username, password) values (19, 'Dr', 'Vasyushkhin');
insert into users (id, username, password) values (20, 'Mr', 'Firebrace');
insert into users (id, username, password) values (21, 'Honorable', 'Suart');
insert into users (id, username, password) values (22, 'Honorable', 'Sneaker');
insert into users (id, username, password) values (23, 'Mrs', 'Guwer');
insert into users (id, username, password) values (24, 'Dr', 'Khomishin');
insert into users (id, username, password) values (25, 'Mr', 'Lartice');
insert into users (id, username, password) values (26, 'Mrs', 'Simonnet');
insert into users (id, username, password) values (27, 'Mr', 'Pohls');
insert into users (id, username, password) values (28, 'Ms', 'Poe');
insert into users (id, username, password) values (29, 'Dr', 'Chopin');
insert into users (id, username, password) values (30, 'Dr', 'Naulty');
insert into users (id, username, password) values (31, 'Rev', 'Joddins');
insert into users (id, username, password) values (32, 'Rev', 'Hanaby');
insert into users (id, username, password) values (33, 'Mr', 'Wallage');
insert into users (id, username, password) values (34, 'Rev', 'Simoneau');
insert into users (id, username, password) values (35, 'Mr', 'Weller');
insert into users (id, username, password) values (36, 'Mrs', 'Gutierrez');
insert into users (id, username, password) values (37, 'Dr', 'Farans');
insert into users (id, username, password) values (38, 'Mr', 'Hardacre');
insert into users (id, username, password) values (39, 'Mr', 'Darton');
insert into users (id, username, password) values (40, 'Rev', 'Lynnett');
insert into users (id, username, password) values (41, 'Honorable', 'Mattielli');
insert into users (id, username, password) values (42, 'Ms', 'Karlolczak');
insert into users (id, username, password) values (43, 'Dr', 'Aveling');
insert into users (id, username, password) values (44, 'Honorable', 'Postles');
insert into users (id, username, password) values (45, 'Rev', 'August');
insert into users (id, username, password) values (46, 'Dr', 'Mallion');
insert into users (id, username, password) values (47, 'Rev', 'Force');
insert into users (id, username, password) values (48, 'Rev', 'Cartmale');
insert into users (id, username, password) values (49, 'Dr', 'Hellyar');
insert into users (id, username, password) values (50, 'Ms', 'Keyhoe');
insert into users (id, username, password) values (51, 'Mrs', 'Swainston');
insert into users (id, username, password) values (52, 'Mr', 'Kelloch');
insert into users (id, username, password) values (53, 'Rev', 'Perche');
insert into users (id, username, password) values (54, 'Ms', 'Kettley');
insert into users (id, username, password) values (55, 'Dr', 'Murty');
insert into users (id, username, password) values (56, 'Mr', 'Abbatini');
insert into users (id, username, password) values (57, 'Dr', 'Roelofsen');
insert into users (id, username, password) values (58, 'Mrs', 'Benneton');
insert into users (id, username, password) values (59, 'Honorable', 'O''Calleran');
insert into users (id, username, password) values (60, 'Dr', 'Ligerton');
insert into users (id, username, password) values (61, 'Mr', 'Harrad');
insert into users (id, username, password) values (62, 'Dr', 'Poynor');
insert into users (id, username, password) values (63, 'Rev', 'Donald');
insert into users (id, username, password) values (64, 'Mrs', 'Tough');
insert into users (id, username, password) values (65, 'Mrs', 'Burberye');
insert into users (id, username, password) values (66, 'Rev', 'Butler');
insert into users (id, username, password) values (67, 'Rev', 'Gerretsen');
insert into users (id, username, password) values (68, 'Mr', 'Lacheze');
insert into users (id, username, password) values (69, 'Mr', 'Linthead');
insert into users (id, username, password) values (70, 'Dr', 'Mepsted');
insert into users (id, username, password) values (71, 'Mrs', 'Newtown');
insert into users (id, username, password) values (72, 'Mrs', 'Ninnoli');
insert into users (id, username, password) values (73, 'Mrs', 'Limbert');
insert into users (id, username, password) values (74, 'Mrs', 'Withrington');
insert into users (id, username, password) values (75, 'Ms', 'Osmant');
insert into users (id, username, password) values (76, 'Ms', 'Tetsall');
insert into users (id, username, password) values (77, 'Mr', 'Threadgall');
insert into users (id, username, password) values (78, 'Ms', 'Shoosmith');
insert into users (id, username, password) values (79, 'Rev', 'Lammert');
insert into users (id, username, password) values (80, 'Dr', 'Higford');
insert into users (id, username, password) values (81, 'Rev', 'Nazareth');
insert into users (id, username, password) values (82, 'Ms', 'Hurkett');
insert into users (id, username, password) values (83, 'Rev', 'Buxam');
insert into users (id, username, password) values (84, 'Mrs', 'Yerill');
insert into users (id, username, password) values (85, 'Ms', 'Clausewitz');
insert into users (id, username, password) values (86, 'Ms', 'Brownsea');
insert into users (id, username, password) values (87, 'Rev', 'Plesing');
insert into users (id, username, password) values (88, 'Dr', 'Wolstenholme');
insert into users (id, username, password) values (89, 'Mr', 'Watterson');
insert into users (id, username, password) values (90, 'Honorable', 'Maulin');
insert into users (id, username, password) values (91, 'Dr', 'Line');
insert into users (id, username, password) values (92, 'Rev', 'Willden');
insert into users (id, username, password) values (93, 'Rev', 'Ryder');
insert into users (id, username, password) values (94, 'Honorable', 'Schwandner');
insert into users (id, username, password) values (95, 'Mr', 'Landor');
insert into users (id, username, password) values (96, 'Rev', 'Gissing');
insert into users (id, username, password) values (97, 'Mr', 'Coffin');
insert into users (id, username, password) values (98, 'Dr', 'Bummfrey');
insert into users (id, username, password) values (99, 'Ms', 'Drysdall');
insert into users (id, username, password) values (100, 'Dr', 'Broseke');

-- Thêm dữ liệu bảng news
insert into news (id, title, content, image, created_at, category_id) values (1, 'Dr', 'Bone marrow transplant rejection', 'http://dummyimage.com/152x100.png/cc0000/ffffff', '2024-04-28 08:30:30', 1);
insert into news (id, title, content, image, created_at, category_id) values (2, 'Ms', 'Nondisplaced fracture of distal phalanx of left index finger, initial encounter for closed fracture', 'http://dummyimage.com/122x100.png/dddddd/000000', '2024-09-03 18:16:55', 2);
insert into news (id, title, content, image, created_at, category_id) values (3, 'Honorable', 'Nondisplaced fracture of medial malleolus of unspecified tibia, subsequent encounter for closed fracture with nonunion', 'http://dummyimage.com/185x100.png/ff4444/ffffff', '2024-07-06 22:53:49', 3);
insert into news (id, title, content, image, created_at, category_id) values (4, 'Dr', 'Unspecified fracture of T11-T12 vertebra, initial encounter for open fracture', 'http://dummyimage.com/195x100.png/dddddd/000000', '2024-11-22 18:40:59', 4);
insert into news (id, title, content, image, created_at, category_id) values (5, 'Rev', 'Laceration of blood vessel of right index finger, subsequent encounter', 'http://dummyimage.com/167x100.png/cc0000/ffffff', '2024-07-30 09:04:20', 5);
insert into news (id, title, content, image, created_at, category_id) values (6, 'Honorable', 'Separation of muscle (nontraumatic), forearm', 'http://dummyimage.com/158x100.png/dddddd/000000', '2024-03-16 01:35:48', 6);
insert into news (id, title, content, image, created_at, category_id) values (7, 'Dr', 'Drowning and submersion while in swimming pool, undetermined intent', 'http://dummyimage.com/146x100.png/5fa2dd/ffffff', '2024-07-31 09:42:04', 7);
insert into news (id, title, content, image, created_at, category_id) values (8, 'Honorable', 'Unspecified injury of flexor muscle, fascia and tendon of left middle finger at forearm level, initial encounter', 'http://dummyimage.com/128x100.png/5fa2dd/ffffff', '2024-05-18 13:54:30', 8);
insert into news (id, title, content, image, created_at, category_id) values (9, 'Dr', 'Other specified fracture of right pubis', 'http://dummyimage.com/183x100.png/dddddd/000000', '2024-11-03 03:42:39', 9);
insert into news (id, title, content, image, created_at, category_id) values (10, 'Rev', 'Foreign body granuloma of soft tissue, not elsewhere classified, left thigh', 'http://dummyimage.com/214x100.png/ff4444/ffffff', '2024-07-18 08:38:08', 10);
insert into news (id, title, content, image, created_at, category_id) values (11, 'Rev', 'Diagnostic and monitoring gastroenterology and urology devices associated with adverse incidents', 'http://dummyimage.com/157x100.png/5fa2dd/ffffff', '2024-05-21 08:27:11', 11);
insert into news (id, title, content, image, created_at, category_id) values (12, 'Honorable', 'Displaced transverse fracture of shaft of left tibia, subsequent encounter for closed fracture with routine healing', 'http://dummyimage.com/226x100.png/cc0000/ffffff', '2024-05-13 03:18:35', 12);
insert into news (id, title, content, image, created_at, category_id) values (13, 'Mrs', 'Toxic effect of fusel oil, assault, initial encounter', 'http://dummyimage.com/169x100.png/dddddd/000000', '2024-01-05 21:48:09', 13);
insert into news (id, title, content, image, created_at, category_id) values (14, 'Mr', 'Poisoning by, adverse effect of and underdosing of other salicylates', 'http://dummyimage.com/190x100.png/dddddd/000000', '2024-02-29 11:54:09', 14);
insert into news (id, title, content, image, created_at, category_id) values (15, 'Mrs', 'Laceration without foreign body of right hand, sequela', 'http://dummyimage.com/176x100.png/cc0000/ffffff', '2024-03-23 08:22:59', 15);
insert into news (id, title, content, image, created_at, category_id) values (16, 'Ms', 'Person on outside of dune buggy injured in nontraffic accident, subsequent encounter', 'http://dummyimage.com/228x100.png/dddddd/000000', '2024-11-22 06:24:03', 16);
insert into news (id, title, content, image, created_at, category_id) values (17, 'Mrs', 'Bloodstream infection due to central venous catheter', 'http://dummyimage.com/223x100.png/dddddd/000000', '2024-02-13 16:49:42', 17);
insert into news (id, title, content, image, created_at, category_id) values (18, 'Mrs', 'Wedge compression fracture of unspecified lumbar vertebra, subsequent encounter for fracture with delayed healing', 'http://dummyimage.com/133x100.png/dddddd/000000', '2024-09-29 23:26:19', 18);
insert into news (id, title, content, image, created_at, category_id) values (19, 'Rev', 'Poisoning by hemostatic drug, undetermined, initial encounter', 'http://dummyimage.com/139x100.png/5fa2dd/ffffff', '2024-06-13 01:00:27', 19);
insert into news (id, title, content, image, created_at, category_id) values (20, 'Honorable', 'Salter-Harris Type I physeal fracture of upper end of unspecified femur, sequela', 'http://dummyimage.com/154x100.png/5fa2dd/ffffff', '2024-08-13 01:57:00', 20);
insert into news (id, title, content, image, created_at, category_id) values (21, 'Ms', 'Complete lesion at unspecified level of thoracic spinal cord, subsequent encounter', 'http://dummyimage.com/205x100.png/5fa2dd/ffffff', '2024-03-20 00:23:18', 21);
insert into news (id, title, content, image, created_at, category_id) values (22, 'Rev', 'Unspecified superficial injury of wrist', 'http://dummyimage.com/143x100.png/5fa2dd/ffffff', '2024-08-24 20:47:08', 22);
insert into news (id, title, content, image, created_at, category_id) values (23, 'Dr', 'Displaced fracture of medial condyle of unspecified femur, subsequent encounter for closed fracture with malunion', 'http://dummyimage.com/181x100.png/dddddd/000000', '2024-01-12 11:17:47', 23);
insert into news (id, title, content, image, created_at, category_id) values (24, 'Dr', 'Injury of musculocutaneous nerve, left arm', 'http://dummyimage.com/145x100.png/5fa2dd/ffffff', '2024-09-16 11:52:53', 24);
insert into news (id, title, content, image, created_at, category_id) values (25, 'Ms', 'Unspecified fracture of unspecified femur, subsequent encounter for open fracture type IIIA, IIIB, or IIIC with nonunion', 'http://dummyimage.com/179x100.png/ff4444/ffffff', '2024-03-08 19:12:15', 25);
insert into news (id, title, content, image, created_at, category_id) values (26, 'Rev', 'Other specified disorders of synovium, left knee', 'http://dummyimage.com/129x100.png/dddddd/000000', '2024-07-02 10:46:40', 26);
insert into news (id, title, content, image, created_at, category_id) values (27, 'Honorable', 'Idiopathic chronic gout, left wrist', 'http://dummyimage.com/222x100.png/ff4444/ffffff', '2024-03-28 02:06:42', 27);
insert into news (id, title, content, image, created_at, category_id) values (28, 'Ms', 'Encounter for examination for recruitment to armed forces', 'http://dummyimage.com/118x100.png/5fa2dd/ffffff', '2024-04-04 03:29:38', 28);
insert into news (id, title, content, image, created_at, category_id) values (29, 'Ms', 'Agalactia', 'http://dummyimage.com/219x100.png/5fa2dd/ffffff', '2024-10-09 06:26:45', 29);
insert into news (id, title, content, image, created_at, category_id) values (30, 'Mr', 'Torus fracture of upper end of left ulna, subsequent encounter for fracture with delayed healing', 'http://dummyimage.com/118x100.png/cc0000/ffffff', '2024-05-29 21:50:35', 30);
insert into news (id, title, content, image, created_at, category_id) values (31, 'Mrs', 'Salter-Harris Type I physeal fracture of left calcaneus, subsequent encounter for fracture with routine healing', 'http://dummyimage.com/220x100.png/5fa2dd/ffffff', '2023-12-19 21:02:54', 31);
insert into news (id, title, content, image, created_at, category_id) values (32, 'Dr', 'Major laceration of carotid artery', 'http://dummyimage.com/239x100.png/5fa2dd/ffffff', '2024-01-14 16:06:16', 32);
insert into news (id, title, content, image, created_at, category_id) values (33, 'Ms', 'Unspecified fracture of upper end of right radius, subsequent encounter for open fracture type I or II with malunion', 'http://dummyimage.com/175x100.png/ff4444/ffffff', '2024-09-25 09:08:31', 33);
insert into news (id, title, content, image, created_at, category_id) values (34, 'Rev', 'Displaced posterior arch fracture of first cervical vertebra, initial encounter for open fracture', 'http://dummyimage.com/220x100.png/dddddd/000000', '2024-05-05 14:37:51', 34);
insert into news (id, title, content, image, created_at, category_id) values (35, 'Mrs', 'Other specified injury of extensor muscle, fascia and tendon of unspecified thumb at wrist and hand level, subsequent encounter', 'http://dummyimage.com/198x100.png/dddddd/000000', '2024-01-28 16:03:46', 35);
insert into news (id, title, content, image, created_at, category_id) values (36, 'Honorable', 'Other specified injury of blood vessel of left index finger, subsequent encounter', 'http://dummyimage.com/130x100.png/ff4444/ffffff', '2024-09-19 01:24:46', 36);
insert into news (id, title, content, image, created_at, category_id) values (37, 'Mrs', 'Jumping or diving from boat striking bottom causing other injury, subsequent encounter', 'http://dummyimage.com/232x100.png/cc0000/ffffff', '2024-05-29 00:13:11', 37);
insert into news (id, title, content, image, created_at, category_id) values (38, 'Dr', 'Other specified rheumatoid arthritis, left knee', 'http://dummyimage.com/237x100.png/5fa2dd/ffffff', '2024-02-14 08:36:54', 38);
insert into news (id, title, content, image, created_at, category_id) values (39, 'Dr', 'Primary blast injury of left ear, subsequent encounter', 'http://dummyimage.com/188x100.png/ff4444/ffffff', '2024-03-19 14:12:36', 39);
insert into news (id, title, content, image, created_at, category_id) values (40, 'Mr', 'Personal history of diseases of the nervous system and sense organs', 'http://dummyimage.com/185x100.png/dddddd/000000', '2024-08-05 05:52:47', 40);
insert into news (id, title, content, image, created_at, category_id) values (41, 'Dr', 'Nonrheumatic mitral (valve) insufficiency', 'http://dummyimage.com/197x100.png/cc0000/ffffff', '2024-09-16 08:50:43', 41);
insert into news (id, title, content, image, created_at, category_id) values (42, 'Ms', 'Toxic effect of ethanol, assault, sequela', 'http://dummyimage.com/211x100.png/dddddd/000000', '2024-03-15 17:42:01', 42);
insert into news (id, title, content, image, created_at, category_id) values (43, 'Rev', 'Traumatic rupture of other ligament of left ring finger at metacarpophalangeal and interphalangeal joint, initial encounter', 'http://dummyimage.com/206x100.png/ff4444/ffffff', '2024-09-30 18:53:54', 43);
insert into news (id, title, content, image, created_at, category_id) values (44, 'Honorable', 'Esophageal obstruction', 'http://dummyimage.com/250x100.png/cc0000/ffffff', '2024-02-14 14:40:01', 44);
insert into news (id, title, content, image, created_at, category_id) values (45, 'Mrs', 'Driver of three-wheeled motor vehicle injured in collision with pedal cycle in nontraffic accident', 'http://dummyimage.com/242x100.png/dddddd/000000', '2024-01-04 10:25:53', 45);
insert into news (id, title, content, image, created_at, category_id) values (46, 'Ms', 'Nondisplaced simple supracondylar fracture without intercondylar fracture of unspecified humerus, initial encounter for open fracture', 'http://dummyimage.com/166x100.png/cc0000/ffffff', '2024-02-19 19:26:29', 46);
insert into news (id, title, content, image, created_at, category_id) values (47, 'Mrs', 'Open bite of unspecified forearm, initial encounter', 'http://dummyimage.com/225x100.png/5fa2dd/ffffff', '2024-11-26 14:34:19', 47);
insert into news (id, title, content, image, created_at, category_id) values (48, 'Dr', 'Strain of unspecified muscle, fascia and tendon at shoulder and upper arm level, unspecified arm, sequela', 'http://dummyimage.com/210x100.png/5fa2dd/ffffff', '2024-08-30 22:25:31', 48);
insert into news (id, title, content, image, created_at, category_id) values (49, 'Rev', 'Nondisplaced fracture of lateral condyle of left tibia, sequela', 'http://dummyimage.com/107x100.png/cc0000/ffffff', '2023-12-23 13:45:47', 49);
insert into news (id, title, content, image, created_at, category_id) values (50, 'Honorable', 'Drowning and submersion due to fall off fishing boat, subsequent encounter', 'http://dummyimage.com/100x100.png/5fa2dd/ffffff', '2024-02-14 03:27:54', 50);
insert into news (id, title, content, image, created_at, category_id) values (51, 'Honorable', 'Continuing pregnancy after intrauterine death of one fetus or more, third trimester, not applicable or unspecified', 'http://dummyimage.com/147x100.png/5fa2dd/ffffff', '2024-11-04 21:12:30', 51);
insert into news (id, title, content, image, created_at, category_id) values (52, 'Mrs', 'Injury of visual cortex, unspecified eye, sequela', 'http://dummyimage.com/145x100.png/ff4444/ffffff', '2024-02-24 19:09:34', 52);
insert into news (id, title, content, image, created_at, category_id) values (53, 'Ms', 'Nondisplaced spiral fracture of shaft of radius, right arm, subsequent encounter for open fracture type IIIA, IIIB, or IIIC with delayed healing', 'http://dummyimage.com/249x100.png/dddddd/000000', '2024-09-07 22:52:49', 53);
insert into news (id, title, content, image, created_at, category_id) values (54, 'Mr', 'Nondisplaced trimalleolar fracture of unspecified lower leg, subsequent encounter for open fracture type I or II with malunion', 'http://dummyimage.com/133x100.png/cc0000/ffffff', '2024-07-17 12:26:00', 54);
insert into news (id, title, content, image, created_at, category_id) values (55, 'Dr', 'Congenital shortening of unspecified upper limb', 'http://dummyimage.com/102x100.png/cc0000/ffffff', '2024-05-28 12:26:00', 55);
insert into news (id, title, content, image, created_at, category_id) values (56, 'Dr', 'Other symptoms and signs involving the nervous and musculoskeletal systems', 'http://dummyimage.com/137x100.png/5fa2dd/ffffff', '2024-10-29 18:58:18', 56);
insert into news (id, title, content, image, created_at, category_id) values (57, 'Mrs', 'Dislocation of radiocarpal joint of left wrist', 'http://dummyimage.com/230x100.png/ff4444/ffffff', '2024-10-05 15:23:06', 57);
insert into news (id, title, content, image, created_at, category_id) values (58, 'Mrs', 'Subluxation of symphysis (pubis) in childbirth', 'http://dummyimage.com/102x100.png/ff4444/ffffff', '2024-04-28 19:50:35', 58);
insert into news (id, title, content, image, created_at, category_id) values (59, 'Mrs', 'Other physeal fracture of upper end of right fibula', 'http://dummyimage.com/174x100.png/5fa2dd/ffffff', '2024-11-08 17:10:47', 59);
insert into news (id, title, content, image, created_at, category_id) values (60, 'Honorable', 'Other chondrocalcinosis, hip', 'http://dummyimage.com/236x100.png/dddddd/000000', '2024-04-19 20:36:46', 60);
insert into news (id, title, content, image, created_at, category_id) values (61, 'Dr', 'Displaced fracture of posterior wall of right acetabulum, subsequent encounter for fracture with routine healing', 'http://dummyimage.com/233x100.png/ff4444/ffffff', '2023-12-07 17:29:22', 61);
insert into news (id, title, content, image, created_at, category_id) values (62, 'Mrs', 'Chronic osteomyelitis with draining sinus, shoulder', 'http://dummyimage.com/160x100.png/dddddd/000000', '2024-03-20 10:53:46', 62);
insert into news (id, title, content, image, created_at, category_id) values (63, 'Mrs', 'Gammaherpesviral mononucleosis without complication', 'http://dummyimage.com/166x100.png/5fa2dd/ffffff', '2024-03-13 20:35:31', 63);
insert into news (id, title, content, image, created_at, category_id) values (64, 'Ms', 'Poisoning by unspecified drugs, medicaments and biological substances, assault, initial encounter', 'http://dummyimage.com/129x100.png/dddddd/000000', '2024-11-08 07:14:20', 64);
insert into news (id, title, content, image, created_at, category_id) values (65, 'Rev', 'Brown-Sequard syndrome at C2 level of cervical spinal cord, subsequent encounter', 'http://dummyimage.com/146x100.png/dddddd/000000', '2024-07-09 11:02:39', 65);
insert into news (id, title, content, image, created_at, category_id) values (66, 'Dr', 'Injury of other blood vessels at lower leg level', 'http://dummyimage.com/211x100.png/dddddd/000000', '2024-01-04 20:23:40', 66);
insert into news (id, title, content, image, created_at, category_id) values (67, 'Rev', 'Abnormal glucose complicating the puerperium', 'http://dummyimage.com/162x100.png/cc0000/ffffff', '2024-05-24 18:34:39', 67);
insert into news (id, title, content, image, created_at, category_id) values (68, 'Mrs', 'Fracture of thoracic vertebra', 'http://dummyimage.com/224x100.png/ff4444/ffffff', '2024-05-03 20:25:55', 68);
insert into news (id, title, content, image, created_at, category_id) values (69, 'Rev', 'Military operation involving nuclear radiation effects of nuclear weapon, civilian, initial encounter', 'http://dummyimage.com/249x100.png/dddddd/000000', '2023-12-25 17:56:25', 69);
insert into news (id, title, content, image, created_at, category_id) values (70, 'Mr', 'Adhesions due to foreign body accidentally left in body following unspecified procedure', 'http://dummyimage.com/127x100.png/ff4444/ffffff', '2024-09-29 16:05:23', 70);
insert into news (id, title, content, image, created_at, category_id) values (71, 'Ms', 'Opioid use, unspecified with intoxication with perceptual disturbance', 'http://dummyimage.com/194x100.png/dddddd/000000', '2024-08-10 05:26:26', 71);
insert into news (id, title, content, image, created_at, category_id) values (72, 'Mr', 'Atherosclerosis of autologous vein bypass graft(s) of the left leg with ulceration of calf', 'http://dummyimage.com/217x100.png/5fa2dd/ffffff', '2024-04-18 03:30:20', 72);
insert into news (id, title, content, image, created_at, category_id) values (73, 'Rev', 'Other specified injury of lesser saphenous vein at lower leg level, unspecified leg, sequela', 'http://dummyimage.com/211x100.png/cc0000/ffffff', '2024-10-15 21:26:37', 73);
insert into news (id, title, content, image, created_at, category_id) values (74, 'Honorable', 'Kaposi''s sarcoma of unspecified lung', 'http://dummyimage.com/201x100.png/cc0000/ffffff', '2024-05-28 18:11:28', 74);
insert into news (id, title, content, image, created_at, category_id) values (75, 'Rev', 'Toxic effect of other halogen derivatives of aromatic hydrocarbons, intentional self-harm, subsequent encounter', 'http://dummyimage.com/120x100.png/ff4444/ffffff', '2024-03-02 20:36:31', 75);
insert into news (id, title, content, image, created_at, category_id) values (76, 'Honorable', 'Salter-Harris Type I physeal fracture of lower end of unspecified femur, initial encounter for closed fracture', 'http://dummyimage.com/131x100.png/ff4444/ffffff', '2024-11-29 18:32:20', 76);
insert into news (id, title, content, image, created_at, category_id) values (77, 'Honorable', 'Emphysema (subcutaneous) resulting from a procedure, sequela', 'http://dummyimage.com/143x100.png/cc0000/ffffff', '2024-07-20 05:04:36', 77);
insert into news (id, title, content, image, created_at, category_id) values (78, 'Honorable', 'Poisoning by pyrazolone derivatives, undetermined, subsequent encounter', 'http://dummyimage.com/173x100.png/5fa2dd/ffffff', '2024-02-19 17:06:38', 78);
insert into news (id, title, content, image, created_at, category_id) values (79, 'Honorable', 'Nondisplaced fracture of neck of fourth metacarpal bone, right hand, subsequent encounter for fracture with routine healing', 'http://dummyimage.com/235x100.png/5fa2dd/ffffff', '2023-12-11 09:16:59', 79);
insert into news (id, title, content, image, created_at, category_id) values (80, 'Mrs', 'Acute postprocedural respiratory failure', 'http://dummyimage.com/186x100.png/dddddd/000000', '2024-06-28 22:03:51', 80);
insert into news (id, title, content, image, created_at, category_id) values (81, 'Mr', 'Unspecified fracture of upper end of left radius, initial encounter for open fracture type IIIA, IIIB, or IIIC', 'http://dummyimage.com/197x100.png/ff4444/ffffff', '2024-08-01 04:32:44', 81);
insert into news (id, title, content, image, created_at, category_id) values (82, 'Dr', 'Injury of other specified blood vessels at shoulder and upper arm level', 'http://dummyimage.com/104x100.png/cc0000/ffffff', '2024-05-28 10:10:16', 82);
insert into news (id, title, content, image, created_at, category_id) values (83, 'Honorable', 'Toxic effect of other ingested (parts of) plant(s), assault, initial encounter', 'http://dummyimage.com/226x100.png/dddddd/000000', '2024-07-15 16:18:50', 83);
insert into news (id, title, content, image, created_at, category_id) values (84, 'Honorable', 'Otosclerosis involving oval window, nonobliterative', 'http://dummyimage.com/244x100.png/dddddd/000000', '2024-05-17 09:57:44', 84);
insert into news (id, title, content, image, created_at, category_id) values (85, 'Ms', 'Subluxation of distal interphalangeal joint of left ring finger, sequela', 'http://dummyimage.com/132x100.png/cc0000/ffffff', '2024-11-20 20:58:39', 85);
insert into news (id, title, content, image, created_at, category_id) values (86, 'Dr', 'Frontotemporal dementia', 'http://dummyimage.com/150x100.png/dddddd/000000', '2024-01-05 18:14:26', 86);
insert into news (id, title, content, image, created_at, category_id) values (87, 'Mrs', 'Abnormal level of enzymes in specimens from female genital organs', 'http://dummyimage.com/230x100.png/dddddd/000000', '2024-09-28 13:12:38', 87);
insert into news (id, title, content, image, created_at, category_id) values (88, 'Mr', 'Collapsed vertebra, not elsewhere classified, sacral and sacrococcygeal region, subsequent encounter for fracture with delayed healing', 'http://dummyimage.com/235x100.png/dddddd/000000', '2023-12-24 01:49:25', 88);
insert into news (id, title, content, image, created_at, category_id) values (89, 'Mr', 'Malignant neoplasm of left optic nerve', 'http://dummyimage.com/219x100.png/cc0000/ffffff', '2023-12-12 18:08:24', 89);
insert into news (id, title, content, image, created_at, category_id) values (90, 'Mr', 'Spontaneous rupture of flexor tendons, multiple sites', 'http://dummyimage.com/102x100.png/ff4444/ffffff', '2024-11-18 13:23:23', 90);
insert into news (id, title, content, image, created_at, category_id) values (91, 'Honorable', 'Chondrolysis, unspecified hip', 'http://dummyimage.com/236x100.png/dddddd/000000', '2024-05-24 07:54:31', 91);
insert into news (id, title, content, image, created_at, category_id) values (92, 'Mrs', 'Open bite of vagina and vulva, subsequent encounter', 'http://dummyimage.com/132x100.png/5fa2dd/ffffff', '2024-10-01 08:22:22', 92);
insert into news (id, title, content, image, created_at, category_id) values (93, 'Rev', 'Poisoning by antiasthmatics, assault, sequela', 'http://dummyimage.com/170x100.png/ff4444/ffffff', '2024-07-08 02:27:12', 93);
insert into news (id, title, content, image, created_at, category_id) values (94, 'Dr', 'Other specified injury of blood vessel of thumb', 'http://dummyimage.com/152x100.png/5fa2dd/ffffff', '2023-12-15 17:42:46', 94);
insert into news (id, title, content, image, created_at, category_id) values (95, 'Ms', 'Other specified injury of intercostal blood vessels, left side, initial encounter', 'http://dummyimage.com/195x100.png/5fa2dd/ffffff', '2024-08-17 21:07:50', 95);
insert into news (id, title, content, image, created_at, category_id) values (96, 'Mrs', 'Unspecified fracture of third thoracic vertebra, initial encounter for open fracture', 'http://dummyimage.com/118x100.png/dddddd/000000', '2024-07-08 07:28:40', 96);
insert into news (id, title, content, image, created_at, category_id) values (97, 'Ms', 'Idiopathic aseptic necrosis of hand and fingers', 'http://dummyimage.com/187x100.png/5fa2dd/ffffff', '2024-09-16 09:56:43', 97);
insert into news (id, title, content, image, created_at, category_id) values (98, 'Honorable', 'Exposure to sudden change in air pressure in aircraft during ascent, initial encounter', 'http://dummyimage.com/243x100.png/cc0000/ffffff', '2023-12-20 04:40:16', 98);
insert into news (id, title, content, image, created_at, category_id) values (99, 'Honorable', 'Calcium deposit in bursa, hip', 'http://dummyimage.com/191x100.png/dddddd/000000', '2024-09-07 12:02:13', 99);
insert into news (id, title, content, image, created_at, category_id) values (100, 'Dr', 'Other traumatic displaced spondylolisthesis of seventh cervical vertebra, subsequent encounter for fracture with nonunion', 'http://dummyimage.com/248x100.png/cc0000/ffffff', '2024-08-23 20:30:39', 100);

--Thêm dữ liệu bảng categories
insert into categories (id, name) values (1, 'Framing (Steel)');
insert into categories (id, name) values (2, 'Rebar & Wire Mesh Install');
insert into categories (id, name) values (3, 'Structural and Misc Steel (Fabrication)');
insert into categories (id, name) values (4, 'Masonry & Precast');
insert into categories (id, name) values (5, 'Prefabricated Aluminum Metal Canopies');
insert into categories (id, name) values (6, 'Masonry');
insert into categories (id, name) values (7, 'Granite Surfaces');
insert into categories (id, name) values (8, 'Marlite Panels (FED)');
insert into categories (id, name) values (9, 'Drywall & Acoustical (FED)');
insert into categories (id, name) values (10, 'Fire Protection');
insert into categories (id, name) values (11, 'RF Shielding');
insert into categories (id, name) values (12, 'Epoxy Flooring');
insert into categories (id, name) values (13, 'Painting & Vinyl Wall Covering');
insert into categories (id, name) values (14, 'Roofing (Metal)');
insert into categories (id, name) values (15, 'Framing (Wood)');
insert into categories (id, name) values (16, 'Glass & Glazing');
insert into categories (id, name) values (17, 'Roofing (Metal)');
insert into categories (id, name) values (18, 'Ornamental Railings');
insert into categories (id, name) values (19, 'Epoxy Flooring');
insert into categories (id, name) values (20, 'Epoxy Flooring');
insert into categories (id, name) values (21, 'EIFS');
insert into categories (id, name) values (22, 'Casework');
insert into categories (id, name) values (23, 'Construction Clean and Final Clean');
insert into categories (id, name) values (24, 'Casework');
insert into categories (id, name) values (25, 'Landscaping & Irrigation');
insert into categories (id, name) values (26, 'Structural & Misc Steel Erection');
insert into categories (id, name) values (27, 'Ornamental Railings');
insert into categories (id, name) values (28, 'Roofing (Asphalt)');
insert into categories (id, name) values (29, 'Drilled Shafts');
insert into categories (id, name) values (30, 'Epoxy Flooring');
insert into categories (id, name) values (31, 'Ornamental Railings');
insert into categories (id, name) values (32, 'Site Furnishings');
insert into categories (id, name) values (33, 'Masonry & Precast');
insert into categories (id, name) values (34, 'Roofing (Asphalt)');
insert into categories (id, name) values (35, 'EIFS');
insert into categories (id, name) values (36, 'Waterproofing & Caulking');
insert into categories (id, name) values (37, 'Wall Protection');
insert into categories (id, name) values (38, 'Drilled Shafts');
insert into categories (id, name) values (39, 'Framing (Wood)');
insert into categories (id, name) values (40, 'Drywall & Acoustical (FED)');
insert into categories (id, name) values (41, 'Ornamental Railings');
insert into categories (id, name) values (42, 'Curb & Gutter');
insert into categories (id, name) values (43, 'Retaining Wall and Brick Pavers');
insert into categories (id, name) values (44, 'Hard Tile & Stone');
insert into categories (id, name) values (45, 'Casework');
insert into categories (id, name) values (46, 'Soft Flooring and Base');
insert into categories (id, name) values (47, 'Masonry & Precast');
insert into categories (id, name) values (48, 'Plumbing & Medical Gas');
insert into categories (id, name) values (49, 'Rebar & Wire Mesh Install');
insert into categories (id, name) values (50, 'Painting & Vinyl Wall Covering');
insert into categories (id, name) values (51, 'Rebar & Wire Mesh Install');
insert into categories (id, name) values (52, 'Roofing (Metal)');
insert into categories (id, name) values (53, 'Marlite Panels (FED)');
insert into categories (id, name) values (54, 'Structural and Misc Steel (Fabrication)');
insert into categories (id, name) values (55, 'Elevator');
insert into categories (id, name) values (56, 'Drywall & Acoustical (MOB)');
insert into categories (id, name) values (57, 'Exterior Signage');
insert into categories (id, name) values (58, 'Roofing (Metal)');
insert into categories (id, name) values (59, 'Waterproofing & Caulking');
insert into categories (id, name) values (60, 'Granite Surfaces');
insert into categories (id, name) values (61, 'Drywall & Acoustical (FED)');
insert into categories (id, name) values (62, 'Structural & Misc Steel Erection');
insert into categories (id, name) values (63, 'Drywall & Acoustical (FED)');
insert into categories (id, name) values (64, 'Drywall & Acoustical (FED)');
insert into categories (id, name) values (65, 'Fire Sprinkler System');
insert into categories (id, name) values (66, 'Marlite Panels (FED)');
insert into categories (id, name) values (67, 'Ornamental Railings');
insert into categories (id, name) values (68, 'Sitework & Site Utilities');
insert into categories (id, name) values (69, 'Electrical');
insert into categories (id, name) values (70, 'Drilled Shafts');
insert into categories (id, name) values (71, 'Drywall & Acoustical (FED)');
insert into categories (id, name) values (72, 'Masonry');
insert into categories (id, name) values (73, 'RF Shielding');
insert into categories (id, name) values (74, 'Framing (Steel)');
insert into categories (id, name) values (75, 'Soft Flooring and Base');
insert into categories (id, name) values (76, 'Structural and Misc Steel (Fabrication)');
insert into categories (id, name) values (77, 'Overhead Doors');
insert into categories (id, name) values (78, 'HVAC');
insert into categories (id, name) values (79, 'RF Shielding');
insert into categories (id, name) values (80, 'Painting & Vinyl Wall Covering');
insert into categories (id, name) values (81, 'Painting & Vinyl Wall Covering');
insert into categories (id, name) values (82, 'Marlite Panels (FED)');
insert into categories (id, name) values (83, 'Glass & Glazing');
insert into categories (id, name) values (84, 'Elevator');
insert into categories (id, name) values (85, 'Drilled Shafts');
insert into categories (id, name) values (86, 'Exterior Signage');
insert into categories (id, name) values (87, 'Electrical');
insert into categories (id, name) values (88, 'Curb & Gutter');
insert into categories (id, name) values (89, 'Structural and Misc Steel (Fabrication)');
insert into categories (id, name) values (90, 'Structural and Misc Steel (Fabrication)');
insert into categories (id, name) values (91, 'EIFS');
insert into categories (id, name) values (92, 'Framing (Steel)');
insert into categories (id, name) values (93, 'Fire Sprinkler System');
insert into categories (id, name) values (94, 'Drywall & Acoustical (FED)');
insert into categories (id, name) values (95, 'Fire Protection');
insert into categories (id, name) values (96, 'Masonry & Precast');
insert into categories (id, name) values (97, 'EIFS');
insert into categories (id, name) values (98, 'Masonry');
insert into categories (id, name) values (99, 'Asphalt Paving');
insert into categories (id, name) values (100, 'Epoxy Flooring');